# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-07-11 11:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clone', '0002_auto_20210711_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='comments',
        ),
    ]
