# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-07-11 11:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clone', '0003_remove_image_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='image',
            name='profile',
        ),
    ]
