# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-07-14 08:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clone', '0004_auto_20210711_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='comments',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='clone.Comments'),
        ),
        migrations.AddField(
            model_name='image',
            name='likes',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='clone.Likes'),
        ),
        migrations.AddField(
            model_name='image',
            name='profile',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='clone.Profile'),
        ),
    ]
